Map language = {
  'en': {
    'dir': true,
    'data': {
      "ComingSoon": "Coming soon",
      "WorkingOnFeature": "We are working on this feature",
      "BetaVersion": "Beta version",
      'Cart': 'Cart',
      'language': 'Language',
      'Setting': 'Setting',
      'Terms': 'Terms and condition',
      'Help': 'Help center',
      'AppInfo': 'App info',
      "writeHere": "write here",
      'PleaseEnterSomeText': "Please enter some text",
      'Send': 'Send',
      "SendAnotherMessage": "Send another message",
      'HistroyPurchase': 'Histroy Purchase',
      'RedeemCodes': 'Redeem codes',
      'Logout': 'Logout',
      'Search': 'Search',
      "Trending": "Trending",
      "Agents": "Agents",
      'Filter': 'Filter',
      "City": "City",
      'Country': 'Country',
      'Price': "Price",
      'Apply': "Apply",
      'NoResultFound': 'No Result Found',
      'AddToCart': 'Add to cart',
      'Recommendations': 'Recommendations',
      "CheckOut": "Check out",
      "EmptyCart": "Empty Cart",
      "GoStartShoping": "Go start shoping",
      "CreateAnAccount": "Create an account",
      'ToStartShopping': 'To start shopping',
      'CreateAccount': 'Create Account',
      'Login': 'Login',
      'ForgotPassword': 'Forgot password',
      'PhoneSendChangePassword':
          "Please enter your phone number below and we will send you an code to change your password.",
      "PhoneNumber": "Phone Number",
      'EmptyPhone': "Please enter phone number",
      'IncorrectPhone': "please enter correct phone number",
      'SendCode': 'Send code',
      "NewPassword": "New Password",
      "Password": 'Password',
      "ConfirmPassword": "Confirm Password",
      'EmptyPassword': 'Please enter password',
      'SmallPassword': "Passwords must be longer than 8 characters.",
      'EmptyRe-password': "Please enter Re-password",
      'PasswordsNotSame': "The passwords are not the same!",
      'PasswordChanged': "Password has been successfully changed",
      'WrongPassword': 'Wrong password',
      "Change": "Change",
      'StartShopping': 'Start Shopping',
      'Register': 'Register',
      'SuspendedAccount': 'Your account has ben suspended',
      "LastName": "Last name",
      "FirstName": "First name",
      'EmptyFirstName': "Please enter first name",
      'EmptyLastName': "Please enter last name",
      'Email': 'Email',
      'EmptyEmail': "Please enter email adress",
      'IncorrectEmail': "Enter your email address correctly",
      "IamAgent": "I am Agent",
      'AccountReady': "Your Account is ready",
      "StartShoping": "Start shoping",
      "Verification": "Verification",
      'Sended4DigitCode': 'We sent you 4 digit code',
      "ResendCode": "Resend code",
      "Welcome": "Welcome",
      "FutureOnlineShopping": "to the future of online shopping",
      "Get Start": "Get Start",
      "Back": "Back",
      'Profile': 'Profile',
      "Edit": "Edit",
      "EmptyNewPassword": "Please enter new password",
      "EmptyOldPassword": "Please enter old password",
      'Update': 'Update',
      "OldPassword": "Old password",
      "EditAccount": "Edit Account",
      "WatingForYou": "we are wating for you",
      "EmptyFavouriteList": "Empty Favourite List",
      'Favourites': 'Favourites',
      'Notification': 'Notification',
      "EmptyNotificationList": "Empty Notification List",
      "NotificationsHere": "Notifications will appear here",
      "TransactionTimeout": "Transaction timeout",
      "ExpiryDate": 'Expiry date',
      'Transaction': 'Transaction',
      'CopiedToClipboard': 'Copied to Clipboard',
      "NoInternet": "No Internet",
      "CouldnotConnectInternet": "Couldn't connect to internet",
      'CheckNetwork': 'Please check your network setting',
      'WelcomeForBuy': 'BizzPayment an app for buying through BizzCoin',
      "Order": "Order",
      'OrderDetail': 'Order Detail',
      'Bizz': 'Bizz',
      'AgentRegister': 'Agent Register',
      'EmptyName': 'Please enter name',
      'Name': 'Name',
      'AgentPendingAccount':
          'Your account has been sent successfully!\nit can take up to 24hrs before accept',
      'Street': 'Street',
      'EmptyStreet': 'Please enter street name',
      'RedeemCode': 'Redeem Code',
      'Code': 'Code',
      'EmptyCode': 'Please enter code',
      'Tap': 'Tap heare to scan qr code',
      'Cancel': 'Cancel',
      'FlashOn': 'Flash on',
      'FlashOff': 'Flash off',
      'Successful': 'Successful',
      'Deposited': 'Bizz deposited',
      'From': 'From',
      'SomethingWrong': 'Something went wrong',
      'TryAgian': 'Try Agian',
      'Description': 'Description',
      'EmptyDescription': 'Please enter description',
      'BuyRedeemCode': 'Buy redeem code',
      "Amount": 'Amount',
      'Buy': 'Buy',
      'EmptyAmount': 'Please enter amount',
      'Previous': 'Previous',
      'TodayValue': 'Today Value',
      'EnterPinCode': 'Enter PIN code',
      'Transfer': 'Transfer',
      'PinCode': 'Pin code',
      'BizzcoinPrice': 'Bizzcoin Price',
      'Grouped': 'Grouped',
      'BetaVer': 'Beta Version',
      'OutOfStock': 'Out Of Stock',
      'EmptyHistoryList':'Your histroy purchase is empty',
      'MyProducts':'My Products',
      'AddProduct':'Add Product',
      'AddPhoto':'Add Photo',
      'ProductName':'Product Name',
      'EmptyProductName': 'Please enter product name',
      'EmptyPrice':'Please enter price',
      "EditProduct":'Edit Product',
      "Save":"Save",
      "DeleteProductDescription":"After deleting there is no way to restore",
      "DeleteProductTitle":"Delete Product",
      "Delete":"Delete",
      "Shop":"Shop",
      "About":'About',
      'UploadPicture':'Upload profile picture',
      'Upload':'Upload',
      'Skip':'Skip',
      'AcceptTerms':'Accept terms and conditions',
      'EmptyTerms':'You must be accept terms and conditions',
      'Empty':"Empty",
      'SelectDate':'SELECT DATE',
      'Ok':'Ok',
      'UpdateSuccess':'Update success'
    },
  },
  'kuk': {
    'dir': true,
    'data': {
      "ComingSoon": "Ji nêzda",
      "WorkingOnFeature": "Em li ser vê taybetmendiyê dixebitin",
      "BetaVersion": "Guhertoya Beta",
      'Cart': 'Ereboka destan',
      'language': 'Ziman',
      'Setting': 'Mîhengkirin',
      'Terms': "Termsert û merc",
      'Help': "Navenda arîkariyê",
      'AppInfo': "Agahdariya app",
      "writeHere": "li vir binivîsin",
      'PleaseEnterSomeText': "Ji kerema xwe hin texmîn binivîsin",
      'Send': "şandin",
      "SendAnotherMessage": "Mesajek din bişînin",
      'HistroyPurchase': "Kirîna Dîrokê",
      'RedeemCodes': "Kodan red bikin",
      'Logout': "Derkeve",
      'Search': "Gerr",
      "Trending": "Xemilandin",
      "Agents": 'ajanên',
      'Filter': "parzûn",
      "City": "Bajar",
      'Country': "Welat",
      'Price': "Biha",
      'Apply': "Bikaranîn",
      'NoResultFound': "Encamek nehat dîtin",
      'AddToCart': "Têxe selikê",
      'Recommendations': "Pêşniyar",
      "CheckOut": "Lêkolîn",
      "EmptyCart": "Qutikek bêkêf",
      "GoStartShoping": "biçin kirînê",
      "CreateAnAccount": "Hesabê çêbikin",
      'ToStartShopping': "ji bo destpêkirina kirînê",
      'CreateAccount': "Hesabê çêbikin",
      'Login': "Têkeftin",
      'ForgotPassword': "Têkeftin",
      'PhoneSendChangePassword':
          "Ji kerema xwe hejmara têlefona xwe li jêr binivîse û em ê ji we re kodek bişînin da ku şîfreya xwe biguhezînin.",
      "PhoneNumber": "Jimare telefon",
      'EmptyPhone': "Ji kerema xwe hejmara telefonê binivîse",
      'IncorrectPhone': "ji kerema xwe hejmara têlefona rast binivîsin",
      'SendCode': "Koda bişînin",
      "NewPassword": "Passwordîfreya Nû",
      "Password": "Şîfre",
      "ConfirmPassword": "di pêşîyê da em sipas dikin",
      'EmptyPassword': "Ji kerema xwe şîfreyê binivîse",
      'SmallPassword': "Divê şîfre ji 8 tîpan zêdetir be.",
      'EmptyRe-password': "Ji kerema xwe dîsa şîfreya xwe binivîse",
      'PasswordsNotSame': "Passwordîfre ne yek in",
      'PasswordChanged': "Şîfre bi serfirazî hate guhertin",
      'WrongPassword': 'Şîfreya çewt',
      "Change": "Hûrkirin",
      'StartShopping': "Firotinê dest pê bikin",
      'Register': "Fêhristkirin",
      'SuspendedAccount': 'Hesabê we hate sekinandin',
      "LastName": "Paşnav",
      "FirstName": "Nav",
      'EmptyFirstName': "Ji kerema xwe navê yekem binivîsin",
      'EmptyLastName': "Ji kerema xwe navê dawîn binivîsin",
      'Email': 'Email',
      'EmptyEmail': "Ji kerema xwe navnîşana e-nameyê binivîsin",
      'IncorrectEmail': "Email rast derbas bikin",
      "IamAgent": "Ez Agent im",
      'AccountReady': "Hesabê we amade ye",
      "StartShoping": "Firotinê dest pê bikin",
      "Verification": "tesdîq",
      'Sended4DigitCode': "Me koda 4-hejmar ji we re şand",
      "ResendCode": "Dîsa kodê ji min re bişînin.",
      "Welcome": "bi xêr hatî",
      "FutureOnlineShopping": "pêşeroja kirîna serhêl",
      "Get Start": "destpêkirin",
      "Back": "Paş",
      'Profile': "Tengal",
      "Edit": "Weşandin",
      "EmptyNewPassword": "Ji kerema xwe şîfreya nû binivîse",
      "EmptyOldPassword": "Ji kerema xwe şîfreya kevin binivîse",
      'Update': 'Nûvekirin',
      "OldPassword": "Passwordîfreya kevn",
      "EditAccount": "Hesabê biguherînin",
      "WatingForYou": "em li benda we ne",
      "EmptyFavouriteList": "Navnîşa xweya bijarte",
      'Favourites': "Sûde",
      'Notification': "Agahdayin",
      "EmptyNotificationList": "Navnîşa agahdariya vala",
      "NotificationsHere": "Nîşan dê li vir xuya bibe",
      "TransactionTimeout": "Demjimêra danûstendinê",
      "ExpiryDate": 'Dîroka qedandinê',
      'Transaction': "Şandindayinî",
      'CopiedToClipboard': 'Li clipboard hate kopî kirin',
      "NoInternet": "pêwendiya înternetê tune",
      "CouldnotConnectInternet": "nikaribû bi înternetê ve girêbide",
      'CheckNetwork': "Ji kerema xwe mîhenga torê ya xwe kontrol bike",
      'WelcomeForBuy': 'BizzPayment an app ji bo kirîna bi rêya BizzCoin',
      "Order": "Emir",
      'OrderDetail': 'Detail Ferman',
      'Bizz': 'Bizz',
      'AgentRegister': 'Tomara Nûnerê',
      'EmptyName': 'Ji kerema xwe navê xwe binivîse',
      'Name': 'Nav',
      'AgentPendingAccount':
          'Hesabê we bi serfirazî hat şandin! berî qebûlkirinê dikare heya 24 saetan bigire',
      'Street': 'Rêgah',
      'EmptyStreet': 'Ji kerema xwe navê kolanê binivîse',
      'RedeemCode': 'Kodê Bikin',
      'Code': 'Code',
      'EmptyCode': 'Ji kerema xwe kodê binivîse',
      'Tap': 'Ji bo şopandina qr qodê li vir bixe',
      'Cancel': 'Bişûndekirin',
      'FlashOn': 'Flash on',
      'FlashOff': 'Flash off',
      'Successful': 'Serfiraz',
      'Deposited': 'Bizz spartin',
      'From': 'Ji',
      'SomethingWrong': 'Tiştek xelet çû',
      'TryAgian': 'Dubare bixebitin',
      'Description': 'Terîf',
      'EmptyDescription': 'Ji kerema xwe danasînê binivîsin',
      'BuyRedeemCode': 'Kodê bikirin',
      "Amount": 'Biha',
      'Buy': 'Kirrîn',
      'EmptyAmount': 'Ji kerema xwe hejmar binivîse',
      'Previous': 'Pêşî',
      'TodayValue': 'Valro Nirx',
      'EnterPinCode': 'PIN-kod binivîse',
      'Transfer': 'Derbaskirin',
      'PinCode': 'Pin code',
      'BizzcoinPrice': 'Bihayê Bizzcoin',
      'Grouped': 'Kom kirin',
      'BetaVer': 'Guhertoya Beta',
      'OutOfStock': 'Balkeş nîne',
      'EmptyHistoryList':'Kirîna dîroka we vala ye',
      'MyProducts':'Berhemên Min',
      'AddProduct':'Hilberê zêde bikin',
      'AddPhoto':'Wêne lê zêde bike',
      'ProductName':'Navê Hilberê',
      'EmptyProductName':'Ji kerema xwe navê hilberê binivîsin',
      'EmptyPrice':'Ji kerema xwe bihayê têkevinê',
      "EditProduct":"Hilbera Hilberandin",
      "Save":'Rizgarkirin',
      "DeleteProductDescription":"Piştî jêbirinê çu rê tune ku meriv vegerîne",
      "DeleteProductTitle":"Hilbera Hilweşînin",
      "Delete":"Jêbirin",
      "Shop":"Dikan",
      "About":"Ji dor",
      'UploadPicture':'Wêneyê profîlê hilkişînin',
      'Upload':'barkirin',
      'Skip':'Hilperkîn',
      'AcceptTerms':'Termsert û mercan qebûl bikin',
      'EmptyTerms':'Divê hûn şert û mercan qebûl bikin',
      'Empty':"Vala ye",
      'SelectDate':'Dîrokê hilbijêrin',
      'Ok':'Ok',
      'UpdateSuccess':'serkeftinê nûve bikin'
    },
  },
  'ar': {
    'dir': false,
    'data': {
      "ComingSoon": "قريبا",
      "WorkingOnFeature": "نحن نعمل على هذه الميزة",
      "BetaVersion": "النسخة التجريبية",
      'Cart': "عربة التسوق",
      'language': 'لغة',
      'Setting': 'ضبط',
      'Terms': "أحكام وشروط",
      'Help': "مركز المساعدة",
      'AppInfo': "معلومات التطبيق",
      "writeHere": "اكتب هنا",
      'PleaseEnterSomeText': "الرجاء إدخال نص",
      'Send': 'إرسال',
      "SendAnotherMessage": "أرسل رسالة أخرى",
      'HistroyPurchase': "شراء التاريخ",
      'RedeemCodes': "رموز الاستخلاص",
      'Logout': "تسجيل خروج",
      'Search': "بحث",
      "Trending": "الشائع",
      "Agents": "عملاء",
      'Filter': "منقي",
      "City": "مدينة",
      'Country': "بلد",
      'Price': "السعر",
      'Apply': "تطبيق",
      'NoResultFound': "لم يتم العثور على نتائج",
      'AddToCart': "أضف إلى السلة",
      'Recommendations': "التوصيات",
      "CheckOut": "الدفع",
      "EmptyCart": "عربة فارغة",
      "GoStartShoping": "ابدأ التسوق",
      "CreateAnAccount": "انشئ حساب",
      'ToStartShopping': "لبدء التسوق",
      'CreateAccount': "انشئ حساب",
      'Login': "تسجيل الدخول",
      'ForgotPassword': "هل نسيت كلمة المرور",
      'PhoneSendChangePassword':
          "الرجاء إدخال رقم هاتفك أدناه وسنرسل لك رمزًا لتغيير كلمة المرور الخاصة بك.",
      "PhoneNumber": "رقم الهاتف",
      'EmptyPhone': "يرجى إدخال رقم الهاتف",
      'IncorrectPhone': "يرجى إدخال رقم الهاتف الصحيح",
      'SendCode': "أرسل الرمز",
      "NewPassword": "كلمة سر جديدة",
      "Password": "كلمه السر",
      "ConfirmPassword": "تأكيد كلمة السر",
      'EmptyPassword': "يرجى إدخال كلمة المرور",
      'SmallPassword': "يجب أن تكون كلمات المرور أطول من ٨ حرف.",
      'EmptyRe-password': "يرجى إدخال كلمة المرور مرة أخرى",
      'PasswordsNotSame': "كلمات السر ليست هي نفسها",
      'PasswordChanged': "كلمه السر تم تغييره بنجاح",
      'WrongPassword': 'كلمة مرور خاطئة',
      "Change": "يتغيرون",
      'StartShopping': "ابدأ التسوق",
      'Register': "تسجيل",
      'SuspendedAccount': 'تم تعليق حسابك',
      "LastName": "الكنية",
      "FirstName": "الاسم الاول",
      'EmptyFirstName': "يرجى إدخال الاسم الأول",
      'EmptyLastName': "يرجى إدخال الاسم الاخير",
      'Email': "البريد الإلكتروني",
      'EmptyEmail': "الرجاء إدخال عنوان البريد الإلكتروني",
      'IncorrectEmail': "أدخل عنوان بريدك الإلكتروني بشكل صحيح",
      "IamAgent": "أنا وكيل",
      'AccountReady': "حسابك جاهز",
      "StartShoping": "ابدأ التسوق",
      "Verification": "التحقق",
      'Sended4DigitCode': "أرسلنا إليك رمزًا مكونًا من ٤ أرقام",
      "ResendCode": "أعد إرسال الرمز",
      "Welcome": "أهلا بك",
      "FutureOnlineShopping": "إلى مستقبل التسوق عبر الإنترنت",
      "Get Start": "ابدأ",
      "Back": "عودة",
      'Profile': "الملف الشخصي",
      "Edit": "تعديل",
      "EmptyNewPassword": "يرجى إدخال كلمة المرور الجديدة",
      "EmptyOldPassword": "يرجى إدخال كلمة المرور القديمة",
      'Update': 'تحديث',
      "OldPassword": "كلمة المرور القديمة",
      "EditAccount": "تحرير الحساب",
      "WatingForYou": "نحن ننتظرك",
      "EmptyFavouriteList": "قائمة المفضلة فارغة",
      'Favourites': "المفضلة",
      'Notification': "تنبيه",
      "EmptyNotificationList": "قائمة الإخطار فارغة",
      "NotificationsHere": "ستظهر الإخطارات هنا",
      "TransactionTimeout": "مهلة المعاملة",
      "ExpiryDate": 'تاريخ الانتهاء',
      'Transaction': "عملية تجارية",
      'CopiedToClipboard': 'نسخ إلى الحافظة',
      "NoInternet": "لا انترنت",
      "CouldnotConnectInternet": "لا يمكن الاتصال بالإنترنت",
      'CheckNetwork': "يرجى التحقق من إعداد الشبكة الخاصة بك",
      'WelcomeForBuy': 'BizzPayment تطبيق للشراء من خلال BizzCoin',
      "Order": "طلب",
      'OrderDetail': 'تفاصيل الطلب',
      'Bizz': 'بیز کوین',
      'AgentRegister': 'سجل الوكيل',
      'EmptyName': "الرجاء إدخال الاسم",
      'Name': 'اسم',
      'AgentPendingAccount':
          'تم إرسال حسابك بنجاح! يمكن أن يستغرق ما يصل إلى 24 ساعة قبل قبول ',
      'Street': 'شارع',
      'EmptyStreet': "الرجاء إدخال اسم الشارع",
      'RedeemCode': "استرداد الرمز",
      'Code': 'الشفرة',
      'EmptyCode': "الرجاء إدخال الرمز",
      'Tap': "انقر هنا لمسح رمز الاستجابة السريعة",
      'Cancel': 'إلغاء',
      'FlashOn': 'تشغيل فلاش',
      'FlashOff': 'إيقاف الفلاش',
      'Successful': 'ناجح',
      'Deposited': 'بیز أودعت',
      'From': 'من عند',
      'SomethingWrong': 'هناك خطأ ما',
      'TryAgian': 'حاول مجددا',
      'Description': 'وصف',
      'EmptyDescription': 'الرجاء إدخال الوصف',
      'BuyRedeemCode': 'شراء رمز استرداد',
      "Amount": 'كمية',
      'Buy': 'يشترى',
      'EmptyAmount': 'الرجاء إدخال المبلغ',
      'Previous': 'السابق',
      'TodayValue': 'قيمة اليوم',
      'EnterPinCode': 'أدخل رمز PIN',
      'Transfer': 'نقل',
      'PinCode': 'الرقم السري',
      'BizzcoinPrice': 'سعر بيزكوين',
      'Grouped': 'مجمعة',
      'BetaVer': 'النسخة التجريبية',
      'OutOfStock': 'إنتهى من المخزن',
      'EmptyHistoryList':'تاريخ الشراء الخاص بك فارغ',
      'MyProducts':'منتجاتي',
      'AddProduct':'أضف منتج',
      'AddPhoto':'إضافة صورة',
      'ProductName':'اسم المنتج',
      'EmptyProductName':'الرجاء إدخال اسم المنتج',
      'EmptyPrice':'الرجاء إدخال السعر',
      "EditProduct":"تحرير المنتج",
      "Save":'حفظ',
      "DeleteProductDescription":"بعد الحذف لا توجد طريقة للاستعادة",
      "DeleteProductTitle":"حذف المنتج",
      "Delete":"حذف",
      "Shop":"متجر",
      "About":"حول",
      'UploadPicture':'تحميل صورة الملف الشخصي',
      'Upload':'رفع',
      'Skip':'تخطى',
      'AcceptTerms':'أوافق على الشروط و الأحكام',
      'EmptyTerms':'يجب أن تقبل الشروط والأحكام',
      'Empty':"فارغة",
      'SelectDate':'حدد تاريخ',
      'Ok':'حسنا',
      'UpdateSuccess':'موفقیت در بروزرسانی'
    },
  },
  'per': {
    'dir': false,
    'data': {
      "ComingSoon": "به زودی",
      "WorkingOnFeature": "ما در حال کار بر روی این ویژگی هستیم",
      "BetaVersion": "نسخه بتا",
      'Cart': "سبد خرید",
      'language': 'زبان',
      'Setting': 'تنظیمات',
      'Terms': "شرایط و ضوابط",
      'Help': "مرکز کمک",
      'AppInfo': "اطلاعات برنامه",
      "writeHere": "اینجا بنویس",
      'PleaseEnterSomeText': "لطفاً متن را وارد کنید",
      'Send': "ارسال",
      "SendAnotherMessage": "پیام دیگری ارسال کنید",
      'HistroyPurchase': "تاریخ خرید",
      'RedeemCodes': "کدها را بازخرید",
      'Logout': "خروج",
      'Search': "جستجو کردن",
      "Trending": "روند",
      "Agents": "نمایندگان",
      'Filter': "فیلتر",
      "City": "شهر",
      'Country': "کشور",
      'Price': "قیمت",
      'Apply': "درخواست دادن",
      'NoResultFound': "هیچ نتیجه ای یافت نشد",
      'AddToCart': "افزودن به سبد خرید",
      'Recommendations': "توصیه ها",
      "CheckOut": "وارسی",
      "EmptyCart": "سبد خرید خالی",
      "GoStartShoping": "برو شروع به خرید",
      "CreateAnAccount": "ایجاد یک حساب کاربری",
      'ToStartShopping': "برای شروع خرید",
      'CreateAccount': "ایجاد حساب کاربری",
      'Login': "وارد شدن",
      'ForgotPassword': "رمز عبور را فراموش کرده اید",
      'PhoneSendChangePassword':
          "لطفاً شماره تلفن خود را در زیر وارد کنید و ما یک کد را برای تغییر رمز عبور برای شما ارسال خواهیم کرد.",
      "PhoneNumber": "شماره تلفن",
      'EmptyPhone': "لطفا شماره تلفن را وارد کنید",
      'IncorrectPhone': "لطفا شماره تلفن صحیح را وارد کنید",
      'SendCode': "ارسال کد",
      "NewPassword": "رمز عبور جدید",
      "Password": "کلمه عبور",
      "ConfirmPassword": "رمز عبور را تأیید کنید",
      'EmptyPassword': "لطفا رمز عبور را وارد کنید",
      'SmallPassword': "گذرواژه‌ها باید بیشتر از ٨ نویسه باشند.",
      'EmptyRe-password': "لطفا دوباره رمز عبور را وارد کنید",
      'PasswordsNotSame': "گذرواژه‌ها یکسان نیستند",
      'PasswordChanged': "کلمه عبور با موفقیت تغییر کرده است",
      'WrongPassword': 'رمز عبور اشتباه است',
      "Change": "تغییر دادن",
      'StartShopping': "خرید را شروع کنید",
      'Register': "ثبت نام",
      'SuspendedAccount': 'حساب شما مسدود شده است',
      "LastName": "نام خانوادگی",
      "FirstName": "نام کوچک",
      'EmptyFirstName': "لطفاً نام خود را وارد کنید",
      'EmptyLastName': "لطفاً نام آخر را وارد کنید",
      'Email': "پست الکترونیک",
      'EmptyEmail': "لطفا آدرس ایمیل را وارد کنید",
      'IncorrectEmail': "ایمیل را به درستی وارد کنید",
      "IamAgent": "من نماینده هستم",
      'AccountReady': "حساب شما آماده است",
      "StartShoping": "خرید را شروع کنید",
      "Verification": "تایید",
      'Sended4DigitCode': "ما کد ٤ رقمی را برای شما ارسال کردیم",
      "ResendCode": "دوباره کد را ارسال کنید",
      "Welcome": "خوش آمدی",
      "FutureOnlineShopping": "به آینده خرید آنلاین",
      "Get Start": "بریم شروع کنیم",
      "Back": "بازگشت",
      'Profile': "مشخصات",
      "Edit": "ویرایش کنید",
      "EmptyNewPassword": "لطفاً رمز جدید را وارد کنید",
      "EmptyOldPassword": "لطفا رمز عبور قدیمی را وارد کنید",
      'Update': "به روز رسانی",
      "OldPassword": "رمز عبور قدیمی",
      "EditAccount": "ویرایش حساب",
      "WatingForYou": "ما منتظرت هستیم",
      "EmptyFavouriteList": "لیست مورد علاقه خالی",
      'Favourites': "موارد دلخواه",
      'Notification': "اطلاع",
      "EmptyNotificationList": "لیست اعلان های خالی",
      "NotificationsHere": "اعلان ها در اینجا ظاهر می شوند",
      "TransactionTimeout": "زمان پایان معاملات",
      "ExpiryDate": 'تاریخ انقضا',
      'Transaction': "معامله",
      'CopiedToClipboard': "در کلیپ بورد کپی شد",
      "NoInternet": "بدون اینترنت",
      "CouldnotConnectInternet": "اتصال به اینترنت امکان پذیر نیست",
      'CheckNetwork': "لطفاً تنظیمات شبکه خود را بررسی کنید",
      'WelcomeForBuy': 'BizzPayment برنامه ای برای خرید از طریق BizzCoin',
      "Order": "سفارش",
      'OrderDetail': 'جزئیات سفارش',
      'Bizz': 'بیز کوین',
      'AgentRegister': 'ثبت نمایندگی',
      'EmptyName': "لطفا نام را وارد کنید",
      'Name': 'نام',
      'AgentPendingAccount':
          'حساب شما با موفقیت ارسال شد! ممکن است قبل از پذیرش 24 ساعت طول بکشد ',
      'Street': 'خیابان',
      'EmptyStreet': 'لطفاً نام خیابان را وارد کنید',
      'RedeemCode': "استفاده از کد",
      'Code': "کد",
      'EmptyCode': 'لطفا کد را وارد کنید',
      'Tap': 'برای اسکن کد qr اینجا ضربه بزنید',
      'Cancel': "لغو",
      'FlashOn': 'فلش بزنید',
      'FlashOff': 'چراغ خاموش',
      'Successful': 'موفقیت آمیز',
      'Deposited': 'بیز سپرده شد',
      'From': 'از جانب',
      'SomethingWrong': 'مشکلی پیش آمد',
      'TryAgian': 'دوباره امتحان کنید',
      'Description': 'شرح',
      'EmptyDescription': 'لطفا توضیحات را وارد کنید',
      'BuyRedeemCode': 'خرید کد استفاده کنید',
      "Amount": 'میزان',
      'Buy': 'خرید',
      'EmptyAmount': 'لطفا مقدار را وارد کنید',
      'Previous': "قبلی",
      'TodayValue': 'امروز ارزش',
      'EnterPinCode': "کد پین را وارد کنید",
      'Transfer': 'انتقال',
      'PinCode': 'کد پین',
      'BizzcoinPrice': 'قیمت بيزكوين',
      'Grouped': 'گروه بندی شده',
      'BetaVer': 'نسخه بتا',
      'OutOfStock': 'تمام شده',
      'EmptyHistoryList':'خرید سابقه شما خالی است',
      'MyProducts':'محصولات من',
      'AddProduct':'افزودن محصول',
      'AddPhoto':'عکس اضافه کنید',
      'ProductName':'نام محصول',
      'EmptyProductName':'لطفا نام محصول وارد کنید',
      'EmptyPrice':'لطفا قیمت را وارد کنید',
      "EditProduct":"ویرایش محصول",
      "Save":'صرفه جویی',
      "DeleteProductDescription":"پس از حذف هیچ راهی برای بازیابی وجود ندارد",
      "DeleteProductTitle":"حذف محصول",
      "Delete":"حذف",
      "Shop":"خرید کنید" ,
      "About":"در باره",
      'UploadPicture':'بارگذاری عکس نمایه',
      'Upload':'بارگذاری',
      'Skip':'پرش',
      'AcceptTerms':'شرایط و ضوابط را بپذیرید',
      'EmptyTerms':'شما باید شرایط و ضوابط را بپذیرید',
      'Empty':"خالی است",
      'SelectDate':'تاریخ را انتخاب کنید',
      'Ok':'خوب',
      'UpdateSuccess':'نجاح التحديث'
    },
  },
  'kus': {
    'dir': false,
    'data': {
      "ComingSoon": "به‌م زوانه‌",
      "WorkingOnFeature": "ئێمه‌ كار له‌م به‌شه‌دا ده‌كه‌ین",
      "BetaVersion": "وه‌شانی كاتی",
      'Cart': 'سه‌به‌ته‌',
      'language': 'زمان',
      'Setting': 'ده‌ستكاری',
      'Terms': "سیاسه‌ت و مه‌رجی به‌كارهێنان",
      'Help': "سه‌نته‌ری هاوكاری",
      'AppInfo': "زانیاری ئه‌پ",
      "writeHere": "لێره‌ بنوسه‌",
      'PleaseEnterSomeText': "تكایه‌ شتێك بنوسه‌",
      'Send': 'ناردن',
      "SendAnotherMessage": "شتێكی تر بنوسه‌",
      'HistroyPurchase': "مێژووی كڕینه‌كانت",
      'RedeemCodes': "كۆده‌ دروستكراوه‌كان",
      'Logout': "چونه‌ده‌ره‌وه‌",
      'Search': "گه‌ڕان",
      "Trending": "گرنگترینه‌كان",
      "Agents": "فرۆشیاره‌كان",
      'Filter': "فلته‌ر",
      "City": "شار",
      'Country': "وڵات",
      'Price': "نرخ",
      'Apply': "جێبه‌جێكردن",
      'NoResultFound': "هیچ ئه‌نجامێك نه‌دۆزرایه‌وه‌",
      'AddToCart': "زیادكردن بۆ سه‌به‌ته‌",
      'Recommendations': "هاوشێوه‌كان",
      "CheckOut": "ژماردن",
      "EmptyCart": "سه‌به‌ته‌ خاڵیه‌",
      "GoStartShoping": "بڕۆ ده‌ست بكه‌ به‌ كڕین",
      "CreateAnAccount": "دروستكردنی هه‌ژمار",
      'ToStartShopping': "بۆ ده‌ستكردن به‌ كڕین",
      'CreateAccount': "دروستكردنی هه‌ژمار",
      'Login': "چوونه‌ژوره‌وه‌",
      'ForgotPassword': "وشه‌ی تێپه‌ڕت بیر چووه‌",
      'PhoneSendChangePassword':
          "تکایە ژماره‌ ته‌له‌فۆنی خۆت داخڵ بکە بۆ ئەوەی كۆده‌ نهێنیەکەت بۆ بنێرین لەڕێگەی ژماره‌ ته‌له‌فۆنه‌كه‌ته‌وه‌",
      "PhoneNumber": "ژماره‌ ته‌له‌فۆن",
      'EmptyPhone': "تكایه‌ ژماره‌ی ته‌له‌فون داخڵ بكه‌",
      'IncorrectPhone': "ژماره‌ی ته‌له‌فوون هه‌ڵه‌یه‌",
      'SendCode': "كۆد بنێره‌",
      "NewPassword": "وشه‌ی تێپه‌ڕی نوێ",
      "Password": "وشه‌ی تێپه‌ڕ",
      "ConfirmPassword": "دوباره‌ وشه‌ی تێپه‌ڕ",
      'EmptyPassword': "تكایه‌ وشه‌ی تێپه‌ڕ داخڵ بكه‌",
      'SmallPassword': "پێویسته‌ وشه‌ی تێپه‌ڕ له‌ ٨ پیت زیاتر بێت",
      'EmptyRe-password': "تكایه‌ دوباره‌ وشه‌ی تێپه‌ڕه داخڵ بكه‌",
      'PasswordsNotSame': "وشه‌ تێپه‌ڕه‌كان یه‌كسان نین",
      'PasswordChanged': "وشه‌ی تێپه‌ڕ به‌سه‌ركه‌وتووی گۆڕدرا",
      "Change": "گۆڕین",
      'StartShopping': "ده‌ست بكه‌ به‌ بازاڕكردن",
      'WrongPassword': 'وشەی تێپەڕ هەڵەیە',
      'Register': "تۆماربوون",
      'SuspendedAccount': 'هەژمارەکەت ڕاگیراوە',
      "LastName": "ناوی باوك",
      "FirstName": "ناوی خۆت",
      'EmptyFirstName': "تكایه‌ ناوی خۆت داخڵ بكه‌",
      'EmptyLastName': "تكایه‌ ناوی باوك داخڵ بكه‌",
      'Email': "ئیمێڵ",
      'EmptyEmail': "تكایه‌ ئیمێڵ داخڵ بكه‌",
      'IncorrectEmail': "ئیمێڵ به‌ دروستی داخڵ بكه‌",
      "IamAgent": "من فرۆشیارم",
      'AccountReady': "هه‌ژماره‌كه‌ت ئاماده‌یه‌",
      "StartShoping": "ده‌ست بكه‌ به‌ بازاڕكردن",
      "Verification": "سه‌لماندن",
      'Sended4DigitCode': "ئێمه‌ كۆدێكی ٤ ژماره‌ییت بۆ ئه‌نێرین",
      "ResendCode": "دوباره‌ كۆدم بۆ بنێره‌",
      "Welcome": "به‌خێربێیت",
      "FutureOnlineShopping": "بۆ داهاتووی كڕینی سه‌رهێڵ",
      "Get Start": "ده‌ست پێكردن",
      "Back": "گه‌ڕانه‌وه‌‌",
      'Profile': "هه‌ژمار",
      "Edit": "نوێ كردنه‌وه‌",
      "EmptyNewPassword": "تكایه‌ وشه‌ی تێپه‌ڕی نوێ داخڵ بكه‌",
      "EmptyOldPassword": "تكایه‌ وشه‌ی تێپه‌ڕی پێشوو داخڵ بكه‌",
      'Update': 'نوێكردنه‌وه‌',
      "OldPassword": "وشه‌ی تێپه‌ڕی پێشوو",
      "EditAccount": "نوێ كردنه‌وه‌ی هه‌ژمار",
      "WatingForYou": "ئێمه‌ چاوه‌ڕێی تۆین",
      "EmptyFavouriteList": "ڵیستی دڵخوازه‌كانت خاڵیه‌",
      'Favourites': "دڵخوازه‌كان",
      'Notification': "ئاگاداركردنه‌وه‌كان",
      "EmptyNotificationList": "ڵیستی ئاگاداریه‌كانت خاڵیه‌",
      "NotificationsHere": "ئگاداریه‌كان لێره‌دا كۆ ده‌بنه‌وه‌",
      "TransactionTimeout": "كاتی مامه‌ڵه‌كه‌ به‌سه‌رچوو",
      "ExpiryDate": 'كاتی به‌سه‌رچوون',
      'Transaction': "مامه‌ڵه‌",
      'CopiedToClipboard': 'کۆدەکە هەڵگیرا',
      "NoInternet": "ئینته‌رنێت نیه‌",
      "CouldnotConnectInternet": "نه‌به‌ستراویته‌وه‌ به‌ هێڵی ئینته‌رنێته‌وه‌",
      'CheckNetwork':
          "تكایه‌ دڵنیا به‌ره‌وه‌ له‌ په‌یوه‌ست بوونت به‌ هێڵی ئینتێرنێته‌وه‌",
      'WelcomeForBuy': 'بیز پەیمێنت ئەپێکە بۆ کڕین لە ڕێگەی بیزکۆینەوە',
      "Order": "داواکاری",
      'OrderDetail': 'زانیاری داواکاریەکان',
      'Bizz': 'بیزکۆین',
      'AgentRegister': 'خۆتۆمارکردنی فرۆشیار',
      'EmptyName': 'تکایە ناو داخڵ بکە',
      'Name': 'ناو',
      'AgentPendingAccount':
          'تۆ هەژمارەکەت بۆ ئێمە نارد ئێمە لە ماوەی ٢٤ کاتژمێردا بەدواداچوون بۆ هەژمارەکەت دەکەین',
      'Street': 'شەقام(ناونیشان)',
      'EmptyStreet': 'تکایە ناونیشان داخڵ بکە',
      'RedeemCode': 'خوێندنەوەی کۆد',
      'Code': 'کۆد',
      'EmptyCode': 'تکایە کۆد داخڵ بکە',
      'Tap': 'کلیک بکە بۆ سکان کردنی کۆد',
      'Cancel': 'داخستن',
      'FlashOn': 'ڕوناککردن',
      'FlashOff': 'تاریککردن',
      'Successful': 'سەرکەوتوو بوو',
      'Deposited': 'بیز بەکارهێنرا',
      'From': 'لە لایەن',
      'SomethingWrong': 'کێشەیەک هەیە',
      'TryAgian': 'دوبارە هەوڵ بە',
      'Description': 'پێناسە',
      'EmptyDescription': 'تکایە پێناسە داخڵ بکە',
      'BuyRedeemCode': 'ڕیدیم کۆد بکڕە',
      "Amount": 'بڕی پارە',
      'Buy': 'کڕین',
      'EmptyAmount': 'تکایە بڕی پارە داخڵ بکە',
      'Previous': 'پێشوتر',
      'TodayValue': 'نرخی ئەمڕۆ',
      'EnterPinCode': 'پین کۆد داخڵ بکە',
      'Transfer': 'گواستنەوە',
      'PinCode': 'پین کۆد',
      'BizzcoinPrice': 'نرخی بیزکۆین',
      'Grouped': 'گروپکراوەکان',
      'BetaVer': 'نەوەی بێتا',
      'OutOfStock': 'لە کۆگادا نەماوە',
      'EmptyHistoryList':'مێژوی کڕینەکانت بەتاڵە',
      'MyProducts':'کاڵاکانم',
      'AddProduct':'زیادکردنی کاڵا',
      'AddPhoto':'وێنە زیاد بکە',
      'ProductName':'ناوی کاڵا',
      'EmptyProductName':'تکایە ناوی کاڵا داخڵ بکە',
      'EmptyPrice':'تکایە نرخ داخڵ بکە',
      "EditProduct":"دەستکاریکردنی کاڵا",
      "Save":"دەستکاری",
      "DeleteProductDescription":"دوای سڕینەوەی ئەم کاڵایە ناتوانی بیگەڕێنیتەوە",
      "DeleteProductTitle":"سڕینەوەی کاڵا",
      "Delete":"سڕینەوە",
      "Shop":"کڕین",
      "About":"دەربارە",
      'UploadPicture':'وێنەیەک دابنێ بۆ هەژمارەکەت',
      'Upload':'دانانی وێنە',
      'Skip':'جێهێشتن',
      'AcceptTerms':'مەرجەکانم قبوڵە',
      'EmptyTerms':'پێویستە بە مەرج و یاساکانمان ڕازی بیت',
      'Empty':"خاڵیە",
      'SelectDate':'کات دیاری بکە',
      'Ok':'تەواو',
      'UpdateSuccess':'نوێکردنەوە سەرکەوتوبو'
    },
  },
};
